### ISSUE TITLE
Members Section Landing Page

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#100]
I think a landing "home page" for the members section would be nice

Right now /members is the How To Join page, and I think it might make more sense to make that at /members/join or something.

Then the landing page can start off directing interested students and parents of new members to their respective pages, then have a section for current members with short summaries and links to the member pages.

Let me know what you think!

**Comment by TJScalzo** [comment]
@rop2000 I would suggest asking things inside of this issue rather than emailing me. That way you can get the opinion of everyone, rather than just my own. I would suggest reading @gisellegk's comment at the top of this issue for information about what to add.

**Comment by rop2000** [comment]
So, if there is any information that you guys feel should be added to the Member Section homepage, just let me know. As Giselle said, we should add a few sentences including a link for anyone who wants to join, parents and current members to make navigation easier. This will all be done hopefully by today.

**Comment by rop2000** [comment]
Finally finished! Homepage for the member section is completed and how to join page has been added under member section category
