### ISSUE TITLE
The footer doesn't stick to the bottom of the page

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#102]
In really short pages (eg. `/members/drive`, ` /members/photos`) the footer sticks to the bottom of the content. Then, there is white space between it and the bottom of the window.

**Comment by TJScalzo** [comment]
I attempted to fix this last meeting but the things I found on the internet didn't provide solutions that worked. This was due to the fact that the footer doesn't have a set height. However, even when I set one it still didn't work. I leave this issue in your care @gisellegk.

**Comment by gisellegk** [comment]
Haha yeah, I tried a couple things and it does some funky stuff... I'll take a closer look today

**Comment by gisellegk** [comment]
@TJScalzo @anusha2617 @poojpooj the changes are live. Can you check on IE/Edge and Safari? I tried Chrome on Android and Firefox and Chrome on Ubuntu. I think it should be fine for modern browsers...

The issue was a white bar below the footer on the [Drive](http://farmingtonrobotics.org/members/drive/) and [Photos](http://farmingtonrobotics.org/members/photos/) pages.

**Comment by TJScalzo** [comment]
Everything appears to be fixed... However, I'd test it on a larger display just in case.

**Comment by TJScalzo** [comment]
I've tested on larger monitors; everything appears to work! Hurray!
