### ISSUE TITLE
Navigation vs. Page Titles Confusing

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#106]
When you're on /about the title says "The 2nd Law Enforcers." Also, clicking "About" brings you to the same page as clicking "The Team."
**List of pages that are confusing:**
- [x] /about - "About" & "The Team" - The 2nd Law Enforcers
- [x] /history - "Team History" - Competition History and Robots
- [x] / - "Home" & "ENFORCERS" - About the Team
- [x] /dreamfirst - "Dream FIRST" - (No title)
- [x] /fll & /flljr - "" - (Inconsistent capitalization)
- [x] /contact - "Contact Us" - Interested in what we’re doing? Want to see us at your school?

So... There're a great deal of pages that have inconsistencies between the navigation bar and the title on the page. I'm sure that's one main thing that should be fixed. However, another thing that could be done is the page you're on is highlighted in the navigation bar when you're on it. (I don't know how that'd work but it would help.)

**Comment by rop2000** [comment]
We should just remove the "The Team" Sub-Category since it should technically be the About tab homepage

**Comment by rop2000** [comment]
I have fixed all the inconsistencies within the various pages.

**Comment by gisellegk** [comment]
@rop2000 Can you reference this issue when you commit so that we know what you did? Just add "#106" anywhere in your commit message (because this is issue #106) and it will automatically link it here.

**Comment by gisellegk** [comment]
@rop2000 Alternatively, since you've already made the commits, you can comment on those commits with #106

**Comment by rop2000** [comment]
Okay, I'll make a mental note to do that from now onwards. Thanks.

**Comment by gisellegk** [comment]
cool. :+1:

On Sat, Feb 13, 2016 at 10:22 PM, Rohan <notifications@github.com> wrote:

> Okay, I'll make a mental note to do that from now onwards. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/106#issuecomment-183811476>
> .
>



-- 
Giselle Koo
