### ISSUE TITLE
Create CSS based SVG animation for use anywhere on site

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#107]
@rop2000 you seem very interested in doing this. However, you seem to be focused on a great many things other than this. I think it'd be great if you spent all of your time on this. The more focused you are, the sooner it'll be finished. By spreading yourself thin between multiple issues you're not focusing on this project.
**Things to animate:**
- [x] Animated flag for in navigation bar
- [ ] Animated Gizmo for 404 page (#82)

**Comment by rop2000** [comment]
@TJScalzo Okay, that sounds good. I am assigned on multiple things but I am doing them one at a time so its focused and the work is good as well. Since I have started a project based on SVG animation, I will focus on this issue first, as you have recommended.

**Comment by TJScalzo** [comment]
I'm just going to close this since it's been a while and no work has been done on it. Also, the website doesn't really need this anyway.
