### ISSUE TITLE
Make link to raffle not show up on raffle page

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#112]
I think something like this would work: (?)
```Javascript
      $("#percent").html("Tickets sold: " + soldPercentShort + "% | $" + money + "+ earned | "+ timeLeft +"{% if page.layout != 'raffle' %}| <a class='raffle-link' href='/raffle'>About the raffle >></a>{% endif %}");
```
I'm not sure if using Liquid would work in Javascript but I feel like it should.

**Comment by gisellegk** [comment]
@TJScalzo I'm not sure if Liquid will work in Javascript. I feel like it won't, but it's definitely worth a shot.

**Comment by TJScalzo** [comment]
@gisellegk Yeah, I'm not sure. I feel like it should because it's injecting the Liquid into the HTML. The problem it probably will run into is the HTML loads after the Liquid runs through it to check for stuff to do.
I'm going to test it and see.

**Comment by TJScalzo** [comment]
I've found a solution!
