### ISSUE TITLE
Several pages of Members section are out of date

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#134]
I noticed these issues when I saw @darrenkwee2 edited parts of the members section recently. If I were still on the team I would fix these issues on my own without consulting anyone. But I'm not part of the team anymore and it would be weird for me to change the content of the website without anyone's input now.

So I'm just making you aware of these issues so that you can decide how best to resolve them as a team. Think about what the purpose of each of these pages is and if it's actually serving that purpose in its current state. Can some pages be consolidated with others or removed entirely? Is there new content that would make these pages useful again?

The pages I would focus on are:
- [How To Join](http://farmingtonrobotics.org/members/join/)
  - Title of page should be "For Prospect**ive** New Members"
  - Contradictory instructions on how to join (join Classroom or email Officers?)
  - Describes joining a mailing list that doesn't exist
  - Links to section of Communication page that doesn't exist (#mail-list)
- [Communication](http://farmingtonrobotics.org/members/communication/)
  - Overall a very specific, empty page with redundant information
  - Mentions a mailing list that doesn't exist
- [Submit Photos](http://farmingtonrobotics.org/members/photos/)
  - Overall a very specific, empty page
  - Links to Drive page that doesn't exist
- [Handbook](http://farmingtonrobotics.org/members/handbook/)
  - Still embedding old version of the handbook 
    - There was a reason that I can't remember...
    - Maybe embedding a PDF vs. a Google Doc?
  - Link to the up-to-date version seems to be old too

**Comment by TJScalzo** [comment]
Issue #77 is where I tracked/explained each of the pages as I was creating the Members section. T
Since this section was first created in 2016, there have been many changes in the team's structure and Google Classroom and Team Drive that I attempted to reflect in periodic updates. But I never took a wholistic look at the section again and made sure its pages referenced each other correctly.

**Comment by TJScalzo** [comment]
One last thing before I leave this issue alone. There are a lot of elements that go into maintaining a website. It can be easy to forget about things when there are so many moving parts. That's what allowed pages of the Members  section to link to pages that no longer exist, I forgot about the. That being said, I probably know the most about this website and what goes into maintaining it. So, I would be happy to review pull requests or chime in with advice on an issue if anyone needs it. I won't be as active as I was when I was on the team, but I really don't want this website to die. So I'll do my best to help.

**Comment by TJScalzo** [comment]
### Embedded Google Docs can't be saved or accessed meaningfully
This issue can be seen on the [Handbook page](http://farmingtonrobotics.org/members/handbook/) and the [Forms page](http://farmingtonrobotics.org/members/forms/). Not only is there no interface for printing or downloading the documents, but if you click a link within an embedded Google Doc it opens within the iframe inside the page. This makes the embeds confusing to interact with and effectively useless in terms of their intended purposes.

The simplest solution that would fix the issue immediately would be embedding PDFs instead of Google Docs. It seems that PDFs embedded from Google Drive automatically come with an interface that lets the user open it in a new tab and/or print it. A slightly more complex solution would be to write a function that allows the user to click a button and print the contents of the iframe that they're looking at. [It's possible](https://stackoverflow.com/questions/9616426/javascript-print-iframe-contents-only), but it requires a complex implementation of JavaScript that isn't at all necessary.

All of this really raises the question, why even embed the documents on the page in the first place? If it creates so much trouble, wouldn't it be better to just give a link to view the documents on Google Drive?

**Important Note:** I would have posted this comment as a separate issue except for the fact that Google Docs are only embedded on pages in the Members section. The ultimate question in this comment relates back to the questions I asked when I first created this issue. What is the purpose of this particular element of the website and why is it necessary? Is there some way it can be simplified so that it is easier to maintain? (Like by having buttons that link directly to the files so that you can take advantage of the interface provided by Google Docs.) Is there new, more up-to-date information from the team that can/should be included here?

**Also,** it's been a year since I posted this issue and there hasn't been much done to address the problems it describes. I understand there's a lot to do, but as a new school year begins this would probably be a good issue to resolve in anticipation of new members joining the team.

**Comment by DoorvaGarg** [comment]
Hi! Just fixed this part up:

- The members tab has been removed since these resources are outdated and can be accessed on classroom (the audience for this tab is just the members of the team anyways, so others do not need access)
- The Handbook (now under About) and Calendar (now under Resources) have been placed under different tabs. 
- The Handbook has been updated to display a PDF (instead of a Google Doc) in an iframe. 

Thank you :)
