### ISSUE TITLE
Newsletter image/link does not show up on mobile

### ISSUE THREAD

**Issue by AM2i9** [team178/team178.github.io#155]
On mobile phones, or screens small enough, the image linking to the newsletter on the main page is hidden. The image probably uses the same CSS properties as the team photo, which also gets hidden once the width of the screen is small enough.

![image](https://user-images.githubusercontent.com/52932656/188526915-7f326ab2-24f1-49d9-8edd-0395c3872ae6.png)

**Comment by DoorvaGarg** [comment]
Thanks! Just fixed it - yeah, the css properties were the reason.
