### ISSUE TITLE
Website Color Discussion

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#21]
@callmeStriking 

[colourcode](http://colourco.de/) and [Adobe Color CC (née Kuler)](https://color.adobe.com/explore/most-popular/?time=all) are very helpful, free systems for choosing more colors. Personally I think the Pure Yellow on the website does not match "Enforcer Gold" and that the approximately Munsell 10B 3/2 that makes up the bar and background is too dark/blue. It looks classy, but maybe too classy. Dunno.

Just for kicks, I decided to try [NCS-ing](https://en.wikipedia.org/wiki/Natural_Color_System) the colors (sans the text) just to see what it looked like. Using the [NCS Premium Navigator](http://www.ncscolour.com/en/premium-navigator/) (for which a free version that lacks color export exists [here](http://www.ncscolour.com/en/ncs-navigator/)), I picked colors NCS S 2060-B, NCS S 0580-Y, and NCS S 3060-B for the slideshow background, Enforcers logo, and nav-bar respectively. (Also, the Enforcers logo's font-weight had to be increased to "normal" to give it some definition. That and I was too lazy to change the text color, which needs a change when the other colors do. Please don't judge the readability of the text because it's not meant to be readable.)

Here's what it looks like.
![2015-02-26-211233_1233x793_scrot](https://cloud.githubusercontent.com/assets/3682844/6406255/24e18a92-bdfc-11e4-9327-d2399485c62e.png)

For comparison, a "before" picture at the same resolution. 
![2015-02-26-211252_1233x793_scrot](https://cloud.githubusercontent.com/assets/3682844/6406256/288a42ce-bdfc-11e4-8736-2a8112afcf3c.png)

It looks really playful and colorful, in my opinion. Instead of adding more colors, it seems that sprucing up the ones we have is also a viable strategy. Clearly the prototype I've presented here needs some work but it's good even as a foil for discussion.

Thoughts?

**Comment by gisellegk** [comment]
@nt1st 

While I do agree with the need for vibrancy, I don't think that it should
come at the cost of brand identity, namely, the trademark Enforcers Blue
and Gold. Here is a Color CC swatch/palate that I made. The comments have
my personal frontrunners http://adobe.ly/183PqzR. If we were to change the
header color to the blue, and add yellow sidebars along the edges of the
content, at perhaps 5px, with a drop shadow onto the gray, then would
achieve slight vibrancy, while more completely representing our brand.
Here's a photoshop mockup. For detail on drop shadow, see the right panel,
as the left one diffused the drop shadow onto the blue header.

**Comment by gisellegk** [comment]
(@nt1st -- please post your images through github, we'd love to see :D)

I think it's not an issue of the current layout color choices, but of the content. I agree with @nt1st about brand identity -- I think the current colors look good together and are designed to be close to our team colors.

A couple years back, I did attempt to make "Design Standards" with official definitions of Enforcer colors (tbh "Enforcer Blue" was #000178, and isn't actually our shirt's blue color but I couldn't pass up the fact that 000178 is a decent shade of blue) 

I like your suggestions, and I also think strategically using graphics would do a lot more for us than making the colors more vibrant.

**Comment by nt1st** [comment]
Hi it took a while for me to get access to my files again. Here is the original comment.
![teamsiteconcept](https://cloud.githubusercontent.com/assets/10603428/6422948/bc4c53de-beac-11e4-9a97-cdfd4f0ea45d.PNG)
"While I do agree with the need for vibrancy, I don't think that it should come at the cost of brand identity, namely, the trademark Enforcers Blue and Gold. Here is a Color CC swatch/palate that I made. The comments have my personal frontrunners http://adobe.ly/183PqzR. If we were to change the header color to the blue, and add yellow sidebars along the edges of the content, at perhaps 5px, with a drop shadow onto the gray, then would achieve slight vibrancy, while more completely representing our brand. Here's a photoshop mockup. For detail on drop shadow, see the right panel, as the left one diffused the drop shadow onto the blue header."

.

**Comment by nt1st** [comment]
This preview has large yellow bars to enhance the contrast. I think they should be a tad bit smaller though.

**Comment by gluxon** [comment]
This issue has been the most active on our team's GitHub so far. I'm not sure what to think of that, but here are my initial thoughts.

While design is extremely important, I think I spent a few years on the team making a mistake with it. FarmingtonRobotics.org and DreamFIRST.org are essentially empty shells. I think they're two of my best works in terms of web design, but both aren't serving their purposes as much as they can. FarmingtonRobotics.org has been getting a lot better recently though thanks to the recent contributors.

I think my advice as spiritual advisor is this: **You're welcome to change the design, but since the current one is modern and updated, let's get some more attention on the other GitHub issues too.**

Thanks everyone.

**Comment by gisellegk** [comment]
Thoughtful consideration of content and how it should be presented (think outside of the wall-of-text box please) will improve the visual impact of the website far more than changing colors. This is an important aspect of "design" that I think has been largely overlooked. Not sure how relevant it is to this thread; I have some suggestions that could be made into new issues and discussed.

**Comment by gluxon** [comment]
I totally agree.

**Comment by gluxon** [comment]
I'm going to close this issue for now since we have issue #33 looking like the continuation of this.
