### ISSUE TITLE
Update picture of robot on header to 2015 robot

### ISSUE THREAD

**Issue by nt1st** [team178/team178.github.io#22]
Here is a new image. The background is a gradient, but I think I can get rid of it with Photoshop if need be.
![f14590fc0266ed256b0710015f2d42ce 1](https://cloud.githubusercontent.com/assets/10603428/6646974/5a0214a8-c9a0-11e4-9289-a272bb72b499.png)

**Comment by gluxon** [comment]
Looks awesome. Would you mind removing the gradient and adding a transparent png to files/robots/TheClawRendering.png?

**Comment by TheKrunch** [comment]
Brandon,
This may be me just being picky but the photo in this email does not have
the upper support things that were added to the gripper.

Matt Scalzo

On Fri, Mar 13, 2015 at 4:55 PM, Brandon Cheng <notifications@github.com>
wrote:

> Looks awesome. Would you mind removing the gradient and adding a
> transparent png to files/robots/TheClawRendering.png?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/22#issuecomment-79384093>
> .
>

-- 


<http://www.fpsct.org>

The documents accompanying this fax or e-mail transmission, including any 
attachments, are for the sole use of the intended recipients and MAY 
contain confidential school, health or other information that is legally 
privileged. The authorized recipient of this information is prohibited from 
disclosing this information to any other party unless required or permitted 
to do so by law or regulation. 

If you are NOT the intended recipient you are hereby notified that ANY 
disclosure, copying, or further distribution of the contents of these 
documents is prohibited. If you have received this information via 
facsimile in error, please notify the sender immediately and arrange for 
the return or destruction of these documents. If information is received 
via e-mail and you are not the intended recipient, please contact the 
sender by e-mail immediately and delete/destroy both the original and the 
reply e-mail message.

**Comment by gluxon** [comment]
@nt1st Rereading your comment, I'm understanding that by "I can get rid of it with Photoshop" you mean that you'll try manually cutting out an alpha layer. You shouldn't have to do that. Audodesk Inventor provides a way to export models against a transparent background. If you're still interested in updating this picture, ask @PrazzleDazzle (Prashant) to help you during the next meeting.

@TheKrunch Yeah, the CAD model posted here isn't very updated at all. Immediately I also noticed that the phalanges aren't triangular and the deckslide is still on in addition to the missing braces you pointed out, but it's no fault of Systems. These changes were made when time was tight.

**Comment by meganlauren1211** [comment]
![the claaaaaaaaw](https://cloud.githubusercontent.com/assets/7004107/6740743/f1080b52-ce58-11e4-9816-7fd460bb2d11.png)

**Comment by meganlauren1211** [comment]
![the actual claw transparent](https://cloud.githubusercontent.com/assets/7004107/6741169/c3421d18-ce5b-11e4-8a13-a0b0e64dd72e.png)
final photo?

**Comment by meganlauren1211** [comment]
changed the photo on the header already
