### ISSUE TITLE
Rename "robots" page

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#25]
The team history page is still at http://farmingtonrobotics.org/robots/

change this to something like "history" maybe?

Here is a tutorial for an easy way to fix this:
https://github.com/blog/1436-moving-and-renaming-files-on-github

**Comment by gisellegk** [comment]
@meganlauren1211 Feel free to assign this task to somebody else -- just wanting to demonstrate/use some of the tools that are a part of github issues.

**Comment by adetoudomkh** [comment]
I fixed the website link from having to type in robots to type in history to go along with the theme of the page. See commit 774cd39
