### ISSUE TITLE
Raffle Meter: Dynamically changing widths of pseudoclasses

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#35]
__Available mentors:__ Giselle Koo
(feel free to add yourself)

[Click here](http://www.w3schools.com/css/css_pseudo_classes.asp) to learn about pseudoclasses.

Currently, we use these lines of code to set the widths of the `:before` and `:after` pseudoclasses:
```javascript
document.styleSheets[7].insertRule(
    '.halfStyle.hs-vertical-third:before { width:' + greenPercent + '%; }', 0);
document.styleSheets[7].insertRule(
    '.halfStyle.hs-vertical-third:after { width:' + purplePercent + '%;  }', 0);
```

1. `document.styleSheets[7]` depends on the fact that the raffle-meter.css file happens to be the 8th spreadsheet on the webpage. If some time in the future we were to add or remove one, our code would not work. __Let's find a way that is not dependent on a hard-coded number.__

2. We've found that `.insertRule()` only works on Chrome. __We need to change this to have support on as many browsers as possible.__

**Comment by TJScalzo** [comment]
We fixed this issue using special JavaScript stuff for FireFox and Chrome. We still need to check if it works on IE. We also need to fix it on Safari.
