### ISSUE TITLE
How to Join page

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#37]
__Available mentors:__ Giselle Koo
(feel free to add yourself)

Quoted from Mr. Barron's email:

>Hi,
>
>Below is an email I sent to a parent who asked about her son joining.  I was thinking it would be cool if we made a webpage that was part of our site called How to Join and put the information I said below on it.  It would be obselete this year soon BUT would be used many times going forward.

**Comment by TJScalzo** [comment]
This seems like it'd be a great thing to do. However, the email that Mr. Barron says he linked isn't in the post above (and I can't seem to find what email this is from). Would it be possible for you to paste in the rest of the email?

**Comment by gisellegk** [comment]
It is just a parent asking how their kid can join.

**Comment by gisellegk** [comment]
The email was only sent to like 3 people or something

**Comment by TJScalzo** [comment]
I was just hoping to use the information that Mr. Barron used. But it sounds like it's not really relevant so I'm okay.

**Comment by gisellegk** [comment]
oh my god sorry! I didn't even read that line of the email lol...

>Hi Sheila,

>There is still time to joing but the time is very short.  We are having our last opportunity for safety training this Saturday 12 -4 pm at our meeting location (the Annex 19 School Street in Unionville.  Safety training is required to be a team member so if Jack can attend the training this Saturday he is good to join. If not, he is welcome to join next year as this is last training we are running for 2015-2016.

>In addition, the school requires that 2 permission forms be completed.  They're are attached with a letter.  The team handbook for parents is also attached.
>We require these forms to be scanned and shared with us using google drive but if Jack brought signed printed versions on Saturday we can show him how to do the rest.

**Comment by TJScalzo** [comment]
Thanks, I'll see if/when I can get to creating this page.

**Comment by gisellegk** [comment]
Not sure who would be interested, but this could also be a good chance to
show someone new how to contribute to the website, rather than always doing
stuff on our own.

Figured I'd mention it since it's a pretty simple task in terms of coding.

On Wed, Dec 2, 2015 at 9:35 PM, Tim Scalzo <notifications@github.com> wrote:

> Thanks, I'll see if/when I can get to creating this page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/37#issuecomment-161498512>
> .
>



-- 
Giselle Koo

**Comment by TJScalzo** [comment]
Sounds like a good idea.

**Comment by Therockster014** [comment]
Did it!

**Comment by gisellegk** [comment]
@Therockster014 @Therockster19  you have two accounts, haha! Let's fix that at the meeting on Monday. (we are meeting on monday right??)

Also, don't forget to click close and comment instead of just comment after you finish a task!

**Comment by Therockster19** [comment]
Closing this issue

**Comment by TJScalzo** [comment]
@Therockster19, I feel like this page should have links to the forms that they have to fill out. I also feel like it could use a header and some rephrasing of sentences. Other than those tweaks I think this is basically done. (You can use [Google](google.com) to learn how to link to the documents or even how to embed them as well as make headers.)

**Comment by gisellegk** [comment]
Can we make a new issue for this? This issue is just to create the page. We can suggest improvements in another one.
