### ISSUE TITLE
Raffle Meter - Font and line height don't work in IE.

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#38]
We need to fix this.

**Comment by TJScalzo** [comment]
I'm not actually sure if this *needs* to be finished before we publish the meter. It seems like not a lot of people use IE anyway. However, if you're going to try and fix this, @gisellegk, go ahead.

**Comment by gisellegk** [comment]
Yeah it does need to get done at some point, IE is popular just because it comes prepackaged with so many computers.... btw it looks fine in Microsoft Edge, which is their new browser for Windows 10

**Comment by gisellegk** [comment]
Getting the font from Adobe now instead of locally, so that works.
Everything else is still terrible though. Thanks for the screenshot @SilverSapo :stuck_out_tongue: 

![2015-11-26](https://cloud.githubusercontent.com/assets/3026367/11428544/7edb9546-943a-11e5-97cb-412193172670.png)

**Comment by gisellegk** [comment]
@TJScalzo @SilverSapo This is the last outstanding issue before we can go live... I can't really do much right now because I don't have a device with IE with me (Thanksgiving travelling...) 

So we need to either fix this, or choose to put the meter online anyways!

**Comment by TJScalzo** [comment]
I also don't have a device with IE on it. I can't do anything to help. I think putting the meter online without fixing this will be fine for now.
