### ISSUE TITLE
Implement raffle meter onto live main page

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#40]
This is the last thing that would need to be done.

**Comment by gisellegk** [comment]
Going to add the small one to the default layout

**Comment by gisellegk** [comment]
Add to homepage in 8f46d82.

Feel free to continue to work on the progress bars! Smash bugs ASAP because they're up for the world to see!

**Comment by TJScalzo** [comment]
The progress div is too far down for some reason. I'm going to fix it.
![screen shot 2015-11-28 at 7 53 28 pm](https://cloud.githubusercontent.com/assets/15825214/11454793/bfd3113e-9609-11e5-8089-b7ffc0ec67b9.png)
