### ISSUE TITLE
Aligning the website with our Team Branding Standards.

### ISSUE THREAD

**Issue by nt1st** [team178/team178.github.io#43]
https://drive.google.com/open?id=1osKZBafFCetyKy_8zcLG-VpnZgxy6UWzadQuC-JZQuI
The colors on the website don't quite align with our team colors. Is this something we want to change?
**To do:**
- [x] Change header's color
- [x] Change footer's color
- [x] Make banner color fit better with header
- [x] Fix contrast of flags
- [x] Make nav bar dropdowns a good color
- [x] Make mobile dropdowns within the nav bar dropdown a good color
- [x] Pick more neutral color for menu icon?
- [x] Make text color change when hovering

**Comment by gisellegk** [comment]
YES!!! PLEASE AND THANK YOU!!! :smile: 

~~also :cry: about depreciating my #000178~~

**Comment by gluxon** [comment]
Go for it. To explain the rationale for the current colors, they were generated from a palette of compatible complementary colors. I would recommend ensuring the same is done of the new colors if they are chosen again.

**Comment by TJScalzo** [comment]
I was thinking we could choose the colors based on the official colors but referencing them with a palette of colors that work together. There are a ton of online palette creators that we can use that let you input a color or two and find others that compliment them.
**Examples:**
* [Coolers](https://coolors.co/)
* [Paletton](http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF)
* [Adobe Color](https://color.adobe.com/create/color-wheel/)

**Comment by TJScalzo** [comment]
I am using these colors for the raffle meter(s):
* ```#000178``` Tickets sold
* ```#FFD000``` Tickets out

[The complete series of colors](https://color.adobe.com/create/color-wheel/?base=2&rule=Complementary&selected=0&name=My%20Color%20Theme&mode=rgb&rgbvalues=0,0.007196614472194168,0.7705882352941176,0.23295481417121738,0.23797583614115642,0.7705882352941176,0,0.004394879066988805,0.47058823529411764,0.83,0.6764258489688632,0,1,0.8149709023721243,0&swatchOrder=0,1,2,3,4): (I realize that I used the "DEPRECATED" blue.)
* ```#3B3DC4``` Light blue
* ```#FFD000``` Light gold
* ```#0002C4``` Bright blue
* ```#D4AC00``` Brown gold
* ```#000178``` Dark blue

**Comment by TJScalzo** [comment]
In trying to fix #58 I've realized that the color of the drop-downs is the same as the background. This doesn't make sense because this makes them just blend into the background. The drop-downs should be a different color. (Might I suggest #D4AC00?) I won't make any changes because I feel like I don't have that authority; I'm just making a suggestion.

**Comment by gluxon** [comment]
Changing the color would be a great suggestion. The original idea was to follow the design idea that menus should match the color of the content it comes from. (You'll see this idea in almost all the operating ststems, Windows 10's black menus being a prime example.) Originally, the navigation didn't overflow, which made visibility fine. Now that they do overflow, I agree, an additional border or change of color would be appropriate.

Also, I would like to share a quote from the bylaws:
> “If the team asks us for our thoughts and advice, we’ve succeeded as a group. If the team asks us for permission or validation, we’ve become exactly what we try to avoid....adult driven.”

Ultimately, the decisions for the website are in your hands Tim. Giselle and I are just here to explain past design decisions and recommend best practices. Take that and apply what you believe is the best action to take.

**Comment by gisellegk** [comment]
(I mean it's worth discussing with @SilverSapo since she's the original Website project leader. But yes you can ask us for advice but we're not decision makers here!)

**Comment by gluxon** [comment]
> (I mean it's worth discussing with @SilverSapo since she's the original Website project leader. But yes you can ask us for advice but we're not decision makers here!)
 
:+1:

**Comment by gisellegk** [comment]
(copied from commit 9b62d12)  

We need to take meeting time (or something) to come up with a stronger/more flexible color palette and update design standards accordingly.

By this I mean going on photoshop and making the colors we need and defining their purposes (eg. links should have consistent colors across the board)

**Comment by poojpooj** [comment]
@anusha2617 & I will work on this

**Comment by TJScalzo** [comment]
The contrast of the banner and the navigation bar is way off. It doesn't look very nice (sorry @anusha2617 and @poojpooj). I was thinking you could change it to ```background-color: rgba(255, 208, 0, .75);``` and the text color to ```color: rgba(255,255,255, 0.8);```.
I've looked at it with those colors on a couple computers and it looks better than what's there right now. I suggest changing to that as soon as possible so that a better combo of blues can be created.

**Comment by gisellegk** [comment]
I agree, the banner and the nav bar colors right now are terrible together... but white text on yellow is not very readable. We could try black text on yellow, which would be readable, but overall I don't think it's much of an improvement over the original blue of the banner.

#color struggles

What I recommend is reaching out to the team. Send an email to the list asking for artsy/design people who are experienced with digital media (web, photoshop, etc.) to help us choose a good color.

**Comment by gisellegk** [comment]
...I'm kind of warming up to the yellow with the blues (but with black text), but I think the blueish white clashes a lot. Maybe if we take a warmer white or a beige as our main neutral color? idk.

**Comment by TJScalzo** [comment]
I think we should revert back to the original colors until we have a definitive color palette that we're using.

**Comment by TJScalzo** [comment]
@nt1st, do you think there're any other issues with branding colors?

**Comment by nt1st** [comment]
The philosophy behind my choosing of our brand colors is to achieve a reasonably close combination of primary colors to the average of our team shirts, adjusting for vibrancy. People know the Enforcers not primary from our digital media, but from seeing our shirts at events and competition. The blue and gold that we wear in real life should be the same blue and gold we wear online.

That said, we may have to diversify our palette for the web medium, because of the sheer number of colors needed. The easiest answer to this is to modify the intensity of the colors we have, by adjusting the K value (CMYK) or adjusting the lightness of the colors we have using the Lightness variable of the colors we have using the HSL model. Ideally we create a few levels of variation with the center color being our primary blue and gold.

**Comment by nt1st** [comment]
I think it would be a good idea to set apart our homepage banner and our nav bar. Perhaps making the nav bar darker, or the banner darker would help.

**Comment by gisellegk** [comment]
> The easiest answer to this is to modify the intensity of the colors we have, by adjusting the K value (CMYK) or adjusting the lightness of the colors we have using the Lightness variable of the colors we have using the HSL model. Ideally we create a few levels of variation with the center color being our primary blue and gold.

This is "easy" to do but very difficult to do *well*. It's super easy to end up with a mediocre color palette by just moving the sliders up and down. I feel like I've been repeating myself on this, but we should *really* see if we can find someone who does a lot of restricted color palette art or something to help us out. 

I found some of [Google's color guidelines](https://www.google.com/design/spec/style/color.html#color-color-palette) geared towards Android app designers. They give us a bunch of premade color palettes, but I would honestly steer away from those (we are Enforcers not Googlers). However, we can use their guidelines after that.

I think using `#0F0838` blue as our primary color and `#FFD000` gold as our accent color would be a good place to start. They then pick 2 more shades around the primary color (one lighter, one darker). These four colors comprise the main color palette. 

They also specify two fallback accent colors:

>Fallback accent colors

>If your accent color is too light or dark to sufficiently contrast with the background color, use a darker or lighter tint of the accent color instead. If your accent color doesn’t work at all, use the 500 version of your primary color on white backgrounds. If your background color is the 500 version of your primary color, make your accent color either white 100% or black 54%.

I think the "pale gold" used as the hover effect on our logo is a good fallback accent color. We could also choose a dark accent color to use as the link color.

Finally, there are the "neutrals". I think we need to lose the off-white light blue thing we've got going on. That color harmonized well with the previous colors, but don't go with our Enforcer blue. [Google has their standard palette of grays](https://www.google.com/design/spec/style/color.html#color-themes) and we can choose to use them or not. I think it would be worth experimenting with really light and/or unsaturated tints of both blue and yellow, or just going with straight up white. 

Font:
>Transparent black or white text behaves more flexibly than grey text because it remains legible and vibrant against background color changes.

:+1: Also, we need to specify details about the fonts we use (Open Sans is fine unless you guys want to change this). We should also specify how much the Stencil font needs to be squished. 

Sectioning the page:
Shadows can be used to distinguish between sections of the app/site. So for us, we could put a shadow between the banner and the body of the page. It could soften the border between blue and `#FFF` white.

**Comment by gisellegk** [comment]
Finally, we need to make sure that our print documents (chairman's stuff, etc.) and pit displays are consistent with these color and font standards. That's outside of the scope of the website of course but still super important.

**Comment by Therockster19** [comment]
I  was thinking for the homepage we could keep the flags in front of the future team photo. Speaking of Team photo do you guys think it's a good idea to have the team photo on the homepage?

**Comment by gisellegk** [comment]
I think it's a great idea! I thought it was going to be under the banner
though... (the one with the flags and Stronghold logo thing) but whichever
looks better!

On Tue, Feb 2, 2016 at 2:10 PM, Mariah Holmes <notifications@github.com>
wrote:

> I was thinking for the homepage we could keep the flags in front of the
> future team photo. Speaking of Team photo do you guys think it's a good
> idea to have the team photo on the homepage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/43#issuecomment-178764018>
> .
>



-- 
Giselle Koo

**Comment by gisellegk** [comment]
@TJScalzo you looked miserable yesterday so I have been experimenting with colors.... let me know what you think @anusha2617 @poojpooj @nt1st 

![screenshot from 2016-02-03 14 56 12](https://cloud.githubusercontent.com/assets/3026367/12795091/753b76a0-ca86-11e5-9c25-5bb033915f4d.png)

**Comment by gisellegk** [comment]
Blues:
#0F0838 - Darkest
#1A245B - Secondary
(I didn't find a need for a very light blue)

Yellows:
#FFD000 - Main
#C09000 - Dark Gold
#fcff5f - Pale Gold

box-shadow: 0px 5px 10px 0px rgba(0,0,0,0.3);

Fonts:
White -   color: rgba(255,255,255, 0.8);
Hover White -   color: rgba(255,255,255, 1);

Black is default black (#000000 or rgba(0, 0, 0, 1) )

Background is just white (#FFFFFF)

**Comment by TJScalzo** [comment]
@gisellegk that looks wonderful! Unless you've already done it, I'll get started on applying those colors into main.css.(?)
**Two Questions:**
- What do you think the combination of colors for the dropdowns should be when on mobile?
- How/where did you apply the box-shadow?

**Comment by gisellegk** [comment]
For the record:
- Committed changes so colors are all set. Sorry forgot to mention in commit message -- 8896520
- We should just make the mobile drop downs not overlap the rest of the navigation
- Box-shadow is applied as inset shadow on top of Banner and outer shadow at bottom of Banner.

**Comment by TJScalzo** [comment]
I'm marking this as complete. Any new problems should be made known in their own issues. I will be working on the dropdowns for the mobile site through issue #96.

**Comment by gluxon** [comment]
Love this.
