### ISSUE TITLE
Timeline Content Clean-up

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#45]
[The timeline](http://farmingtonrobotics.org/history/) could use some love in terms of content. We did a great job of hashing out all the events we need on there, but adding pictures, videos, and text would be awesome!

#31 is specifically about the content about each year's game that is copied from the game manual.

This issue addresses the broken picture links (or lack of pictures in general). We can also include videos! And finally, a lot of the events are only titles... if we can add descriptions that would be great!

**Comment by TJScalzo** [comment]
I'll try and update is as much as possible. I think it might be getting a little crowded though. Perhaps I could make another one that's specifically about all the things that happened/are happening this season? I'm not really sure if that's needed I just think it might help with how filled it appears to be.
Also, here's the link to some sort of [template](https://docs.google.com/document/d/1pv9CWmjNYiNu6CRca97r7FfXM0E3_O7RRmmM0leM8Ys/edit#) for the timeline and the [spreadsheet](https://docs.google.com/spreadsheets/d/1gAQk8B-cUymb1d2vw6caLEU6keI2if1xm4RKEzc3MCI/edit#gid=0) that controls the events. If anyone else wants to add information that I'll inevitably miss feel free.

**Comment by gisellegk** [comment]
FYI, I think @poojpooj might have been going through and at the very least, removing broken pictures and moving the others to the /assets/img/ folder, to help with #66 .

I think making a timeline for this season's events in addition to a larger-scale one is a good idea. I also think it'd be cool if we made our own timeline, so that we could make it look exactly the way we want it to. It would be a lot of work, but we could make something super awesome looking. But if you (or someone else) don't want to bother, then that's fine.
