### ISSUE TITLE
Moving links to modular CSS...?

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#46]
I guess this is mostly to @gluxon but is it better to put modified CSS for different layouts in main.css or in their own separate CSS files?

Either way I think it'd still be better to move the css and javascript links out of raffle-meter.html in _includes... probably should be moved into the head section of raffle-meter.html file in _layouts.

**Comment by gluxon** [comment]
> I guess this is mostly to @gluxon but is it better to put modified CSS for different layouts in main.css or in their own separate CSS files?

It really depends. I originally meant for main.css to be something that only styled the top level main structural items, but already does more than that. I would say if something could be moved into its own file, go for it. Although many different opinions exist among professional web developers, and most are valid.

> Either way I think it'd still be better to move the css and javascript links out of raffle-meter.html in _includes... probably should be moved into the head section of raffle-meter.html file in _layouts.

Absolutely. I would agree. A quick nitpick I would point out is that `includes/raffle-meter.html` currently has jQuery 1.11 included. jQuery 2.1 is in `includes/head.html` as well. If jQuery has been giving you guys trouble, that may have caused it.
