### ISSUE TITLE
Add non-popup information around the raffle meter

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#49]
This should be pretty quick -- most difficult part will be making it calculate the # of days left. (raffle drawing is Dec. 10)

#### Raffle Progress Bar
(Mouse over the logo for details.) 
### ENFORCERS
Tickets Sold: 6% of goal | (#) days left! | Click here to learn about the raffle >>

**Comment by TJScalzo** [comment]
Should it also be mentioned that they have to have tickets in by Dec 3?

**Comment by SilverSapo** [comment]
I think that it should so it's a reminder to all team members and it tells people when our sales end.
