### ISSUE TITLE
Create smaller meter for other pages

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#50]
The large raffle meter is too big to be used on all of the pages of the site. Therefore we should create a meter that is smaller and more easily understandable. I suggest a rectangle meter with words that explain what's happening inside of it. It shouldn't be as based off of text; therefore, it should be less intrusive.
**To Do:**
- [x] Brainstorm what it'd look like
- [x] Figure out how to implement it
- [x] Implement it
- [x] Do a bunch of debugging
- [ ] Make drop-downs not be covered

**Comment by gisellegk** [comment]
I'm envisioning a thin bar of just white, yellow, and blue, and a link that says something along the lines of "About the raffle >>" either centered below the line, or aligned to the far right.

Where would we put it? Right below the navigation bar, or above it?

**Comment by TJScalzo** [comment]
I feel like it'd work in between the header/navigation bar and the "slideshow"

-Tim

**Comment by TJScalzo** [comment]
My question(s) is: How would this be done? Should I add to the default layout and have something like ```{% include raffle-meter-s.html %}```? Or should I do it some other way? (Right now, that's the only way I can think of doing it.)

**Comment by gisellegk** [comment]
I'd say adding it to the default layout would be easiest... and we can also make another layout called "Small Meter" or something, so that when we change the default layout back to normal, we won't lose our code.

**Comment by TJScalzo** [comment]
Okay, I've fixed the issue where nothing would show up for either test page. However, I think the way that I'm trying to do it won't work. I don't really know *why* it won't work; I just have this feeling that no matter how hard I try, adding everything to the existing JavaScript and CSS won't work.

**Comment by TJScalzo** [comment]
Because different browsers affect the header's height differently, I can't tell the meter to go down a cetatin amount because that amount would be different in another browser. 
Chrome V
![screen shot 2015-11-27 at 5 40 44 pm](https://cloud.githubusercontent.com/assets/15825214/11448784/2b21fc84-952e-11e5-86b1-0872eaaa556a.png)
Safari V
![screen shot 2015-11-27 at 5 40 18 pm](https://cloud.githubusercontent.com/assets/15825214/11448797/90733daa-952e-11e5-83a6-0a82e6e6b955.png)

**Comment by TJScalzo** [comment]
I'm going to look into creating ```@media``` queries (browser queries) that will check for the browser type *as well as* a certain width.

**Comment by TJScalzo** [comment]
Another thing that I've tried is putting the status divs (out and sold) inside of the goal div. However, they still go to the top of the page. I *think* they way I'd fix this is by using a clear element that forces them to stay inside their parent div. 
HTML
```<div class="parent">
   <img class="floated_child" src="..." />
   <span class="clear"></span>
</div>```
CSS
```span.clear { clear: left; display: block; }```
I tried to use ```overflow: hidden``` but it didn't work. I'll try later tonight to figure this out. If anyone knows a way to fix this... please.

**Comment by TJScalzo** [comment]
Everything about this is working properly except for the fact that the drop-downs for the About and Member Section are covered by it. In fact, you can't even use them because they disappear when you go over the raffle meter.
I've been trying to figure out how I could get the meter to go underneath them; however, due to the fact that it's made up of three divs that would go underneath each other incorrectly if their z-indexes were changed to a negative, I haven't been able to fix it. I've tried setting the z-index of the drop-down but that doesn't seem to work either.
@gisellegk and/or @gluxon, I realize it's super **duper** late. But when you see this can you try and help?
