### ISSUE TITLE
Meter extends too far on larger displays

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#54]
I've actually got no idea how to fix this. The problem comes from the fact that I opened the meter on my dad's computer that has a gi***gantic*** screen. The meter extends very far on each side of the area  that actually has content. This is due to the fact that vw makes the word "Enforcers" *just* tall enough to reach each side of the window. However, on a screen as big as my dad's it's unwise to do that because it takes up most of the page that way.
**Therefore**, we need to find a way to have it stop extending the height once it reaches a certain point.

**Comment by TJScalzo** [comment]
In reading the internet I feel like I can do something with ```@media ```. If I'm wrong then I reiterate: I have no idea how to fix this. The only other thing I can think of is the way that the header stays at a certain width. However, I don't know how that works so someone with better experience really needs to help with this. Can you help me @gisellegk and/or @gluxon?

**Comment by gisellegk** [comment]
A possible solution could be limiting how large the text size can be?

**Comment by TJScalzo** [comment]
I've figured out how I'm going to do it. All I have to do now is implement it properly. It's too late tonight to tediously go through everything. Instead, I'm pasting the code here so I don't lose it and I'm going to bed.

```
@media (min-width: 1200px) {
	.halfStyle.hs-vertical-third {
    position:relative;
    display:inline-block;
    font-family: "Stencil Std";
    font-size:15.5vw; /* or any font size will work */
    overflow-y:visible;
    pointer-events: none;
    white-space: pre; /* to preserve the spaces from collapsing */
    color: #FFF; /* for demo purposes */
    text-shadow:
        -0.25vw -0.25vw 0 #000,
         0.25vw -0.25vw 0 #000,
        -0.25vw 0.25vw 0 #000,
         0.25vw 0.25vw 0 #000;
 }
}
```
**Things to Figure Out:**
* How wide the limit of the meter should be
* At what window size it should change to the limited width
* If anything else needs to be fixed to make this better (like the line thickness)
* If this could be used in the opposite way to make the meter better on mobile (to change the line thicknesses a little, see #55)

**Comment by TJScalzo** [comment]
I decided that another half hour couldn't hurt so I wrote this:
```
@media (min-width: 1300px) {
    .halfStyle.hs-vertical-third {
    font-size:200px; /* or any font size will work */
    text-shadow:
        -2px -2px 0 #000,
         2px -2px 0 #000,
        -2px 2px 0 #000,
         2px 2px 0 #000;
    }
    .halfStyle.hs-vertical-third:before {
    text-shadow:
        -3px -3px 0 #fdd51b,
         3px -3px 0 #fdd51b,
        -3px 3px 0 #fdd51b,
         3px 3px 0 #fdd51b;
    }
    .halfStyle.hs-vertical-third:after { /* creates the right part */
    text-shadow:
        -3px -3px 0 #fdd51b,
         3px -3px 0 #fdd51b,
        -3px 3px 0 #fdd51b,
         3px 3px 0 #fdd51b;
    }
}
```
It seems to work fairly well. The only problem is when I entered it into the page using Chrome's developer tools, the "(Mouse over the logo for details)" gets put into the same line as "Enforcers" for some reason. I'm too tired to fix it right now.

**Comment by gisellegk** [comment]
I just changed the font size from vw to vmin -- so on mobile it is based on width, but on a desktop computer it's based on height.... can you test to see if this helps @TJScalzo ?

**Comment by gisellegk** [comment]
Sorry I hope I'm not like pulling the rug out from under you on this one... you did a lot of great work! Plus my fix might not work anyways.... 

but your `@media` work will still definitely help with #55 outline problem !

**Comment by TJScalzo** [comment]
It seems to help a little bit. However, if you go into landscape mode on mobile or resize the window on desktop too much it starts to look too small. Also, on my dad's giant display things just look strange. I think ```@media``` will work if I just take half an hour and figure out the best limits to use.

**Comment by gisellegk** [comment]
I think it honestly looks huge especially compared to the rest of the stuff on the page.....

**Comment by TJScalzo** [comment]
I was talking about the fact that everything runs into itself. The margins seem to be messed up. I'm going to undo the vmins and add some stuff so that I can see if using ```@media``` will help.

**Comment by gisellegk** [comment]
Go for it :+1:

**Comment by TJScalzo** [comment]
@gisellegk if you still think it looks too big, feel free to scale things down by changing the font size a little. Otherwise, I think everything's fixed here.
