### ISSUE TITLE
The meter looks strange on smaller screens/mobile devices

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#55]
Basically, the viewport width becomes so small that the width of the outlines becomes zero and so that needs to be fixed. Not only that but the progress lines of text wrap badly. Also, the mouse over logo for details text should be removed in mobile.

**Comment by TJScalzo** [comment]
![image](https://cloud.githubusercontent.com/assets/15825214/11415274/f2e126de-93ce-11e5-9d3b-2b0ecb3cb671.png) (An example of what I'm talking about.)

**Comment by gisellegk** [comment]
Made font size responsive (6b0fe47a)... should help with the text wrapping

**Comment by TJScalzo** [comment]
I'm going to use '''@media''' to make the outline change when on mobile.

**Comment by TJScalzo** [comment]
The titles also get too small. (I think "Raffle Progress Bar!" stays the mostly the same size?)
![image](https://cloud.githubusercontent.com/assets/15825214/11430238/8c323008-9451-11e5-9470-ad322746bf82.png)Portrait ^
![image](https://cloud.githubusercontent.com/assets/15825214/11430239/8c407672-9451-11e5-99e6-12ad08741eef.png)Landscape ^

**Comment by gisellegk** [comment]
Also looks weird but in a different way for me...  For mobile, I want the raffle bar to go all the way across the screen, but for desktop computers it should just go as wide as the text in the "slideshow"

Portrait:
![img_1438](https://cloud.githubusercontent.com/assets/3026367/11430784/dc26f88e-9459-11e5-8782-6e108b1fbe88.PNG)

Landscape:
![img_1439](https://cloud.githubusercontent.com/assets/3026367/11430785/dc293bbc-9459-11e5-831f-7a10330790be.PNG)

**Comment by TJScalzo** [comment]
That's strange... I think it's because the font height is set to vw? It's like some of the text-shadow is showing up and some isn't; which is sort of like what happens on my phone. I'll try to fix it once I get to a computer.

**Comment by TJScalzo** [comment]
Alright. I think it's fixed. If the "Tickets sold: 7.5% | 14 days left! | About the raffle >>" and/or the "Raffle Progress Bar!" looks to big/small at larger/smaller sizes then reopen this issue and let me know.
