### ISSUE TITLE
Make the percentage round to 2 decimal places

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#62]

**Comment by gisellegk** [comment]
nice job! :+1:

**Comment by TJScalzo** [comment]
I'll add the code to the small raffle meter now. I forgot to before.

**Comment by gisellegk** [comment]
I bet we can find a way to make the two meters share code (like using if statements possibly in places where they do different things) so that we don't have to fix stuff in two places...

**Comment by TJScalzo** [comment]
Yeah, I'm not sure why I immediately jumped to splitting them into separate code. I'm not sure of the exact issues that I faced when trying to put them in the same file (I've wiped the bad memories away). But I feel like at least one of them was that I couldn't apply a styleSheetElement to multiple tags. Would me need to maybe make a separate sheet to be added to the code? Like this maybe?
```javascript
  var sheet1 = new StyleSheet();
  var widthSold = new StyleSheetElement("width", soldPercent + '%');
  var tagA = sheet1.addElementToTag(".halfStyle.hs-vertical-third:before", widthSold);
  var widthOut = new StyleSheetElement("width", outPercent + '%');
  var tagB = sheet1.addElementToTag(".halfStyle.hs-vertical-third:after", widthOut);
  console.log(sheet1);
  addInlineStyleSheet(sheet1);

  var sheet2 = new StyleSheet();
  var widthSold = new StyleSheetElement("width", soldPercent + '%');
  var tagC = sheet2.addElementToTag(".halfStyle.hs-vertical-third:before", widthSold);
  var widthOut = new StyleSheetElement("width", outPercent + '%');
  var tagD = sheet2.addElementToTag(".halfStyle.hs-vertical-third:after", widthOut);
  console.log(sheet2);
  addInlineStyleSheet(sheet2);

**Comment by TJScalzo** [comment]
Also, do we still need ```console.log(sheet)```? I feel like that was just for when we weren't sure if it was working. I mean, it wouldn't really change much. But it *might* speed the program up a little?

**Comment by gisellegk** [comment]
(btw we should probs make a new issue lol...)

I think putting them in separate files to begin with was a totally fine move -- it helps you figure out what's going on. It's not a bad thing to go back and improve your code like we are now... 

no, you are right, we don't need `console.log` . I doubt it would speed up the script by any noticeable amount but it's still clutter that we don't need.

I don't think we should have a problem putting them both on the same sheet... maybe something like this:
```
  var sheet = new StyleSheet();

  var widthSold = new StyleSheetElement("width", soldPercent + '%');
  var tagA = sheet1.addElementToTag(".halfStyle.hs-vertical-third:before", widthSold);
  var tagC = sheet2.addElementToTag("#raffle-meter-sold", widthSold);

  var widthOut = new StyleSheetElement("width", outPercent + '%');
  var tagB = sheet1.addElementToTag(".halfStyle.hs-vertical-third:after", widthOut);
  var tagD = sheet2.addElementToTag("#raffle-meter-out", widthOut);

  addInlineStyleSheet(sheet);
```

I mean I don't know, but if I had to guess, you might have tried something like this: 
`var tagA = sheet1.addElementToTag(".halfStyle.hs-vertical-third:before", "#raffle-meter-out",  widthSold);` which probably wouldn't work.

**Comment by gisellegk** [comment]
edit again: re-reading your comment, you might have tried the thing I just suggested... sooo idk we can experiment!

**Comment by gisellegk** [comment]
Ok seriously why can't I find any documentation on the `.addElementToTag` function??
