### ISSUE TITLE
I feel like there're too many layouts

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#65]
The homepage.html and the raffle-meter.html are the exact same document. It makes me wonder if there's something special about the homepage's layout or if it can use the default (except for right now because of the raffle meter. But couldn't it just use the raffle-meter layout?) I don't understand why there are some many layouts when they're all basically the same.
**Suggestions/Questions:**
* Delete homepage layout and replace with raffle-meter layout
* What's the fullpage layout for? Why don't all of the pages use it?

I don't really know if this should be considered an issue; it just bothers me a little.

**Comment by gisellegk** [comment]
homepage.html was for the potential that the homepage could look radically different (?) from all the other pages... eg. see discussion from like last spring...issues #28 #33 ???

So yeah right now it's pretty useless.

**Comment by gisellegk** [comment]
Fullpage layout is used in [Team History](http://farmingtonrobotics.org/history/) to allow content to span the entire width of the screen, rather than having generous margins like the rest of the pages.

**Comment by SilverSapo** [comment]
I was thinking of maybe adding some sort of slideshow for the main pages we want to show off. Right now, there's just content on it.

**Comment by gisellegk** [comment]
I think improving the home page with steps like the one @SilverSapo mentioned above ^ are definitely something that we need to pursue...

**Comment by SilverSapo** [comment]
I also need something on how people can join the team. As of right now, there is only contacting us through email. Are there any other steps that are needed that might require a separate page for the process?

**Comment by gisellegk** [comment]
@SilverSapo see #37

**Comment by SilverSapo** [comment]
@gisellegk Thanks

**Comment by gisellegk** [comment]
Closing because there seems to be nothing more to do. @TJScalzo let me know if you think there's unfinished business with this issue

**Comment by nt1st** [comment]
Anyone can join our email list. The link I sent to you in an email about
the email list and the Google Drive folder are valid for all.
