### ISSUE TITLE
There are a lot of missing images

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#66]
There are a ton of images that are being pulled from off of the website (from facebook mostly) that no longer load. We need to either fix the links or find new images to replace them. The website looks unfinished when boxes with a single word in them load instead of images.

**Comment by gluxon** [comment]
Did you manage to resolve this? Was this only for the hofc page?

**Comment by TJScalzo** [comment]
No this is for everywhere. On the about page. On the timeline. There are missing images scattered everywhere.

**Comment by gluxon** [comment]
Those images are pointing to facebook images generated by a Facebook session. Only the person that's logged in under that session id is going to be able to view them. (It's like sending someone a link to your gmail inbox.) I suggest downloading the photos and uploading them to /assets.

**Comment by gisellegk** [comment]
The hard part will be figuring out what those pictures were lol.

I think the student that put the images there probably got them from the "milestones" on the Facebook page (eg., https://www.facebook.com/509649582391248/posts/524887790867427/ was probably on the about page)

**Comment by nt1st** [comment]
You could check the wayback machine on the internet archive.

**Comment by TJScalzo** [comment]
What does that mean?

**Comment by gisellegk** [comment]
@nt1st That was the first thing I tried lol... no luck :(

**Comment by TJScalzo** [comment]
I did make the Gizmo image work, that's good. But I don't know what the other image is supposed to be.

**Comment by gisellegk** [comment]
lol the old title was better :stuck_out_tongue: 

Can we go through the entire website and make a list of where the broken images are? And at this point, if we don't know what it used to be then we should just delete it or replace it with something suitable. Probably better to have up-to-date images anyways.

**Comment by TJScalzo** [comment]
I'll see if I can do that. However, I'm pretty swamped right now so maybe someone else can? @SilverSapo?

**Comment by gisellegk** [comment]
Maybe we should see if there's anyone else on the team interested in doing website stuff.... I'm gonna start a google doc writing a recruitment email and share it with you guys

**Comment by gisellegk** [comment]
@Therockster19 do you think you could help us with this task? Just click through the pages, and if you find a broken picture, just post the link here!
