### ISSUE TITLE
Blue font link color is hard to read on dark blue background

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#67]
On the small raffle-meter.

I can fix this, but I'm not sure what to change it to...

**Comment by TJScalzo** [comment]
Maybe make it one of the gold colors I suggested in #43?

**Comment by TJScalzo** [comment]
I'm going to close this because it doesn't overlap the blue anymore. If you still think this is a problem feel free to open this again.

**Comment by gisellegk** [comment]
I think it's a good habit to code for any/every possible case. Like if we were to sell 100% of the tickets, for example, then there would definitely be overlap.

**Comment by TJScalzo** [comment]
I don't know what color to make. I tried different variations of gold/yellow and blue. I don't want to use a different color because it would detract from the theme. However, I'm beginning to feel like I might have to. What color(s) would you suggest?

**Comment by gisellegk** [comment]
I wonder if making it bold will help?

**Comment by TJScalzo** [comment]
That might work... Would that be something with text-weight?
