### ISSUE TITLE
Edit content of "How To Join" page

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#72]
@TJScalzo 
> @Therockster19, I feel like this page should have links to the forms that new members have to fill out. I also feel like it could use a header and some rephrasing of sentences. Other than those tweaks I think this is basically done. (You can use Google to learn how to link to the documents or even how to embed them as well as make headers.)

- [x] Rephrase sentences
- [x] Link to forms
- [x] Link to join team shared folder
- [x] Link to join email list
- [x] Link to join email list for parents
- [X] Make the email address obfuscated

**Comment by gisellegk** [comment]
@nt1st Can you post the link for joining the email list in this thread?

**Comment by TJScalzo** [comment]
I'll do it.

**Comment by TJScalzo** [comment]
There:
[Team Shared Folder](https://drive.google.com/open?id=0B8-N1pSXiqwhb2diaHFIdWtoY0k)
[Email List](https://groups.google.com/forum/#!forum/farmingtonrobotics)
[Email List for Parents](https://groups.google.com/forum/#!forum/farmington-robotics-team-parents)
