### ISSUE TITLE
Update/re-do the drive page for Team Drive

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#79]
Add more information on how permissions/organization works in the folder.

**Comment by poojpooj** [comment]
@anusha2617 and I will work on this

**Comment by gisellegk** [comment]
@poojpooj @TJScalzo Are we not doing this issue? If so, let's close it. Otherwise, use the "on hold" tag

**Comment by TJScalzo** [comment]
@gisellegk, according to several people we've talked to: "Explaining the organization of the drive isn't something that can be done easily." I might just add a line that says not to mess with any files unless you've talked to the people who are using them.

**Comment by TJScalzo** [comment]
This issue is covered by #134 which is more general.
