### ISSUE TITLE
Remove Raffle Meter from Website?

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#81]
It's been about a month since the raffle ended. Should we remove it from the website?

**Comment by TJScalzo** [comment]
I've asked for the info but no one's gotten back to me.

**Comment by gisellegk** [comment]
Let's remove it then. Assigning this task to @poojpooj

**Comment by gisellegk** [comment]
@poojpooj Good job!

**Comment by TJScalzo** [comment]
Hurray!
