### ISSUE TITLE
Move HoC site to a separate repo

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#84]
It will still be at farmingtonrobotics.org/hofc, but the code won't be mixed up with the rest of the site.

**Comment by gisellegk** [comment]
Left the redirect but everything else is in the [new repository](https://github.com/team178/hofc) :)

**Comment by TJScalzo** [comment]
@gisellegk, the redirect page (from /hoc to /hofc) is still in the main repository. Should it get removed and the hofc repository renamed?

**Comment by gisellegk** [comment]
Wasn't sure -- I just preserved the current functionality of the site. Do you think it *should* be /hoc? cause in that case, yes let's do that.

**Comment by TJScalzo** [comment]
I think it'd make more sense for it to just be /hoc. That way everything to do with Hour of Code is in its own repo without intersecting with the main one.
