### ISSUE TITLE
Improve the Media page

### ISSUE THREAD

**Issue by anusha2617** [team178/team178.github.io#87]
- [x] Add pictures (slideshow?) from recent events
- [x] Turn videos into carousel/slideshow
- [x] Change link to YouTube to look nicer

**Comment by TJScalzo** [comment]
Hey, @anusha2617 can you describe what you're going to do to improve the page? I'd like to understand what your plan is.

**Comment by anusha2617** [comment]
Hey @TJScalzo , I had a few ideas:
* there are no pictures (but there are videos), so we could possibly add some from recent events
* we could change the link to the YouTube page to make it look prettier, so there could be something like "Check out our YouTube page!" and we could link the YouTube page to the word YouTube...?
* instead of having the videos just there, if possible, we could make them look more organized by being able to scroll through them to have one video at a time playing
* the whole list [link](https://docs.google.com/document/d/1my3oZXPNErfxgMsPB7V970u3Nrl7hwAohOb0Dfk49KI/edit)

**Comment by TJScalzo** [comment]
@anusha2617, you can look into the [BXSlider](http://bxslider.com) to see how you'd make the videos and/or pictures part of a slideshow.

**Comment by gisellegk** [comment]
Super excited to see this come together!

**Comment by gisellegk** [comment]
Maybe add "click here to see all of our albums" after the picture album, that links to all our Facebook albums. (((Which, by the way, means we need to actually HAVE Facebook albums..........lol.........)))
