### ISSUE TITLE
Add Chairman's Award to Timeline

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#90]
It's important that this get added soon. Yes, I realize there's already an issue that already says this (#31); however, that's just a general issue and this is a _specific_ thing that needs be added as soon as possible.
I'm giving this issue to @poojpooj because she needs something to do.

@poojpooj, talk to people and ask around for information on the Chairman's award. Heck, while you're at it ask about any other content that could be added. (But do this first.)

**Comment by gisellegk** [comment]
:+1: We won Chairman's at the Pioneer Valley District Qualifier in Springfield, MA last year. A lot of people cried. We had a video that was shown to everyone. It was kind of hacked together last minute, and I think a recording of me my Junior year was in it. Don't actually say that on the website please lol. Anyways it qualified us to compete at the New England District Championships. Let me know if you need to know anything else.
