### ISSUE TITLE
Committees page kinda out-of-date

### ISSUE THREAD

**Issue by Elizabeth-Cho** [team178/team178.github.io#94]
So this page may need some updating because it mentions that we're still in 525. The other information is probably still fine.

**Comment by nt1st** [comment]
We no longer use the committee system. We have managers of different areas of the team. Perhaps this should be reorganized to reflect that.

**Comment by TJScalzo** [comment]
So... how should this be restructured? I'm not really sure what you want it to look like now, @nt1st. I can at least assume you want it to be called something other than Committees, though I'm not sure what you want it changed to.

**Comment by gisellegk** [comment]
@TJScalzo @nt1st wondering if there's a draft of bylaws with descriptions of the manager system floating around somewhere??

**Comment by TJScalzo** [comment]
@gisellegk Not as far as I know. Although, I'm not really in any position where I would know if there were. This sits on @nt1st's shoulders now.

**Comment by nt1st** [comment]
Hi Guys,
@TJScalzo There are draft documents with descriptions of the Manager system, and the management areas. This page would best be restructured with a replacement of the Committee names with the new management area names. Here are the nine area names.

1. Robot Components
2. Robot Support
3. Team Member Support
4. Fundraising
5. Dream FIRST
6. Programming
7. Public Relations
8. Media Production
9. Systems

**Comment by TJScalzo** [comment]
Now that we've migrated back to the committees system the page is most likely fine. However, it could probably do with some slight updates in regards to the descriptions.

**Comment by TJScalzo** [comment]
I'm closing this because its contents are out of date and irrelevant to the current team structure. See #125.
