### ISSUE TITLE
Fix nav bar's dropdowns in general

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#96]
On mobile the dropdowns have arrows but instead of pointing to the menu icon or the text they came from, they over to the right.
![image](https://cloud.githubusercontent.com/assets/15825214/12697188/dd20e97e-c74a-11e5-9205-8db8c8e9a08c.png)
![image](https://cloud.githubusercontent.com/assets/15825214/12697189/dd312140-c74a-11e5-8732-90f255e9e48e.png)

**Comment by TJScalzo** [comment]
The secondary dropdowns should either be a different color from the main nav bar dropdown or come out the side rather than down.

**Comment by TJScalzo** [comment]
Copied from #43:
> - We should just make the mobile drop downs not overlap the rest of the navigation

**Comment by gisellegk** [comment]
Woohoo! :tada:
